"""empty message

Revision ID: 514350a1f02f
Revises: 6cf75eef979a
Create Date: 2021-07-23 07:35:55.163817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514350a1f02f'
down_revision = '6cf75eef979a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('order_date', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'order_date')
    # ### end Alembic commands ###
